#!/usr/bin/env python3
"""
FlexConsensus - FASE 2a: Ejecutar HetSIREN
============================================
Entrena HetSIREN en cada dataset para generar el primer espacio latente.

HetSIREN usa redes SIREN (sinusoidal representation networks) que trabajan
en espacio real para reconstruir volúmenes heterogéneos.

Salida: Espacio latente de HetSIREN como .txt para FlexConsensus

Uso:
  python scripts/03_run_hetsiren.py --dataset IgG-RL --gpu 0
  python scripts/03_run_hetsiren.py --dataset all --gpu 0,1
"""

import argparse
import os
import sys
import subprocess
import json
import glob
import numpy as np
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
RESULTS_DIR = PROJECT_DIR / "results"
TOOLKIT_DIR = PROJECT_DIR / "SOFTWARE" / "Flexutils-Toolkit"

# Hiperparámetros por dataset (del paper)
HETSIREN_CONFIGS = {
    "IgG-RL": {
        "het_dim": 4,         # Dimensión del espacio latente
        "epochs": 50,
        "batch_size": 8,
        "lr": 1e-5,
        "architecture": "convnn",
        "ctf_type": "apply",
        "pad": 2,
        "num_vol": 10,        # Volúmenes a decodificar vía K-Means
        "cost_function": "corr",
        "description": "IgG-RL: 4D latent, conformación 1D conocida",
    },
    "MDSpike": {
        "het_dim": 8,
        "epochs": 50,
        "batch_size": 8,
        "lr": 1e-5,
        "architecture": "convnn",
        "ctf_type": "apply",
        "pad": 2,
        "num_vol": 20,
        "cost_function": "corr",
        "description": "MDSpike: 8D latent, múltiples conformaciones",
    },
    "Ribosome-80S": {
        "het_dim": 10,
        "epochs": 30,
        "batch_size": 8,
        "lr": 1e-5,
        "architecture": "convnn",
        "ctf_type": "wiener",
        "pad": 2,
        "num_vol": 20,
        "cost_function": "corr",
        "description": "Ribosome 80S: 10D latent, datos experimentales",
    },
    "Spike-SARS2": {
        "het_dim": 10,
        "epochs": 30,
        "batch_size": 8,
        "lr": 1e-5,
        "architecture": "convnn",
        "ctf_type": "wiener",
        "pad": 2,
        "num_vol": 20,
        "cost_function": "corr",
        "description": "Spike SARS-CoV-2: 10D latent, reemplazo D614G",
    },
}

ALL_DATASETS = ["IgG-RL", "MDSpike", "Ribosome-80S", "Spike-SARS2"]


def log(msg):
    print(f"[HETSIREN] {msg}", flush=True)


def find_metadata_file(preproc_dir):
    """Busca o genera el archivo de metadatos Xmipp para HetSIREN."""
    # HetSIREN espera un archivo de metadatos Xmipp (.xmd o .star)
    xmd_files = glob.glob(str(preproc_dir / "*.xmd"))
    if xmd_files:
        return xmd_files[0]

    star_files = glob.glob(str(preproc_dir / "*.star"))
    if star_files:
        return star_files[0]

    return None


def create_xmipp_metadata(preproc_dir, particles_mrcs, poses_pkl, ctf_pkl, output_xmd):
    """
    Genera un archivo de metadatos Xmipp a partir de los archivos preprocesados.
    Esto permite alimentar HetSIREN sin necesitar Scipion.
    """
    import pickle

    log("  Generando metadatos Xmipp...")

    # Cargar poses
    with open(poses_pkl, "rb") as f:
        rotations = pickle.load(f)   # (N, 3, 3) rotation matrices
        translations = pickle.load(f)  # (N, 2) translations

    # Cargar CTF
    with open(ctf_pkl, "rb") as f:
        ctf_params = pickle.load(f)  # (N, 9) CTF parameters

    n_particles = len(rotations)
    log(f"  Partículas: {n_particles}")

    # Convertir rotation matrices a Euler angles (rot, tilt, psi)
    from scipy.spatial.transform import Rotation as R
    euler_angles = R.from_matrix(rotations).as_euler('ZYZ', degrees=True)

    # Escribir archivo Xmipp metadata (.xmd)
    with open(output_xmd, "w") as f:
        f.write("; Xmipp metadata generated by FlexConsensus pipeline\n")
        f.write("; HEADER\n")
        f.write(" ; _image\n")
        f.write(" ; _angleRot\n")
        f.write(" ; _angleTilt\n")
        f.write(" ; _anglePsi\n")
        f.write(" ; _shiftX\n")
        f.write(" ; _shiftY\n")
        f.write(" ; _ctfDefocusU\n")
        f.write(" ; _ctfDefocusV\n")
        f.write(" ; _ctfDefocusAngle\n")
        f.write(" ; _ctfVoltage\n")
        f.write(" ; _ctfSphericalAberration\n")
        f.write(" ; _ctfQ0\n")
        f.write(" ;\n")

        for i in range(n_particles):
            img_ref = f"{i+1:06d}@{particles_mrcs}"
            rot, tilt, psi = euler_angles[i]
            sx, sy = translations[i] if i < len(translations) else (0, 0)
            # CTF: columns are [D, Apix, defU, defV, defAngle, kV, Cs, ampContrast, phaseShift]
            defU = ctf_params[i, 2] if i < len(ctf_params) else 20000
            defV = ctf_params[i, 3] if i < len(ctf_params) else 20000
            defAngle = ctf_params[i, 4] if i < len(ctf_params) else 0
            kV = ctf_params[i, 5] if i < len(ctf_params) else 300
            Cs = ctf_params[i, 6] if i < len(ctf_params) else 2.7
            ampC = ctf_params[i, 7] if i < len(ctf_params) else 0.1

            f.write(f" {img_ref}  {rot:.4f}  {tilt:.4f}  {psi:.4f}  "
                    f"{sx:.4f}  {sy:.4f}  {defU:.2f}  {defV:.2f}  "
                    f"{defAngle:.4f}  {kV:.1f}  {Cs:.2f}  {ampC:.4f}\n")

    log(f"  Metadatos Xmipp escritos: {output_xmd} ({n_particles} partículas)")
    return output_xmd


def run_hetsiren(dataset_name, gpu="0"):
    """Ejecuta HetSIREN para un dataset específico."""
    config = HETSIREN_CONFIGS[dataset_name]
    result_dir = RESULTS_DIR / dataset_name
    preproc_dir = result_dir / "preprocessed"
    hetsiren_dir = result_dir / "hetsiren"
    hetsiren_dir.mkdir(parents=True, exist_ok=True)

    log(f"\n{'='*60}")
    log(f"HETSIREN: {config['description']}")
    log(f"{'='*60}")

    # Verificar que el preprocesamiento se completó
    meta_file = preproc_dir / "preprocess_meta.json"
    if not meta_file.exists():
        log(f"ERROR: No se encontró {meta_file}")
        log(f"Ejecuta primero: python scripts/02_preprocess.py --dataset ...")
        return False

    # Verificar si ya se completó
    latent_output = hetsiren_dir / "latent_space.txt"
    if latent_output.exists():
        log(f"HetSIREN ya completado para {dataset_name}. Saltando.")
        log(f"  (Elimina {latent_output} para re-ejecutar)")
        return True

    # Buscar archivos de entrada
    particles_mrcs = list(preproc_dir.glob("particles_*.mrcs"))
    if not particles_mrcs:
        log(f"ERROR: No se encontraron partículas downsampled en {preproc_dir}")
        return False
    particles_mrcs = str(particles_mrcs[0])

    poses_pkl = preproc_dir / "poses.pkl"
    ctf_pkl = preproc_dir / "ctf.pkl"

    # Buscar o crear metadata Xmipp
    md_file = find_metadata_file(preproc_dir)
    if md_file is None:
        if poses_pkl.exists() and ctf_pkl.exists():
            md_file = str(preproc_dir / "particles_metadata.xmd")
            create_xmipp_metadata(preproc_dir, particles_mrcs, poses_pkl, ctf_pkl, md_file)
        else:
            log("ERROR: No se encontraron poses/CTF ni metadata Xmipp")
            return False

    # Detectar pixel size
    with open(meta_file) as f:
        meta = json.load(f)
    pixel_size = meta.get("pixel_size", 1.0)
    box_size = meta.get("box_size", 128)

    # --- ENTRENAR HETSIREN ---
    log(f"  Entrenando HetSIREN (het_dim={config['het_dim']}, epochs={config['epochs']})...")

    train_script = TOOLKIT_DIR / "tensorflow_toolkit" / "scripts" / "train_het_siren.py"

    train_args = [
        sys.executable, str(train_script),
        "--md_file", str(md_file),
        "--out_path", str(hetsiren_dir),
        "--batch_size", str(config["batch_size"]),
        "--shuffle",
        "--split_train", "0.9",
        "--pad", str(config["pad"]),
        "--sr", str(pixel_size),
        "--apply_ctf", "1",
        "--het_dim", str(config["het_dim"]),
        "--lr", str(config["lr"]),
        "--epochs", str(config["epochs"]),
        "--cost", config["cost_function"],
        "--architecture", config["architecture"],
        "--ctf_type", config["ctf_type"],
        "--tensorboard",
        "--gpu", str(gpu),
    ]

    log(f"  Comando: {' '.join(train_args[:6])}...")
    result = subprocess.run(train_args, capture_output=True, text=True)

    if result.returncode != 0:
        log(f"  ERROR en entrenamiento:")
        log(f"  {result.stderr[-500:]}")
        # Guardar error log
        with open(hetsiren_dir / "train_error.log", "w") as f:
            f.write(result.stdout + "\n" + result.stderr)
        return False

    log("  Entrenamiento completado!")

    # --- PREDECIR (extraer espacio latente) ---
    log("  Extrayendo espacio latente...")

    predict_script = TOOLKIT_DIR / "tensorflow_toolkit" / "scripts" / "predict_het_siren.py"
    weights_file = list(hetsiren_dir.glob("network/*het_siren*"))
    if not weights_file:
        weights_file = list(hetsiren_dir.glob("network/*.h5"))
    if not weights_file:
        log("  ERROR: No se encontraron pesos del modelo")
        return False
    weights_file = str(weights_file[0])

    predict_args = [
        sys.executable, str(predict_script),
        "--md_file", str(md_file),
        "--weigths_file", weights_file,
        "--pad", str(config["pad"]),
        "--sr", str(pixel_size),
        "--apply_ctf", "1",
        "--het_dim", str(config["het_dim"]),
        "--num_vol", str(config["num_vol"]),
        "--gpu", str(gpu),
    ]

    result = subprocess.run(predict_args, capture_output=True, text=True)
    if result.returncode != 0:
        log(f"  ERROR en predicción: {result.stderr[-300:]}")
        return False

    # --- EXTRAER ESPACIO LATENTE COMO .TXT ---
    # HetSIREN guarda el espacio latente en la metadata de las partículas
    # Lo extraemos como .txt para que FlexConsensus lo use
    log("  Exportando espacio latente a .txt...")

    latent_data = extract_hetsiren_latent(md_file, hetsiren_dir)
    if latent_data is not None:
        np.savetxt(latent_output, latent_data, fmt="%.8f")
        log(f"  Espacio latente guardado: {latent_output} (shape: {latent_data.shape})")
    else:
        log("  WARNING: No se pudo extraer espacio latente automáticamente")
        log("  Deberás extraerlo manualmente del archivo de metadatos")

    # Guardar metadatos del run
    run_meta = {
        "method": "HetSIREN",
        "dataset": dataset_name,
        "config": config,
        "weights_file": weights_file,
        "latent_shape": list(latent_data.shape) if latent_data is not None else None,
    }
    with open(hetsiren_dir / "run_meta.json", "w") as f:
        json.dump(run_meta, f, indent=2)

    log(f"  HetSIREN completado para {dataset_name}!")
    return True


def extract_hetsiren_latent(md_file, output_dir):
    """
    Extrae el espacio latente de HetSIREN desde la metadata actualizada.
    HetSIREN añade columna 'latent_space' al archivo de metadata.
    """
    try:
        # Intentar leer como Xmipp metadata
        latent_values = []
        with open(md_file, "r") as f:
            for line in f:
                line = line.strip()
                if line.startswith(";") or not line:
                    continue
                parts = line.split()
                # Buscar columna latent_space (formato: [v1,v2,...,vN])
                for part in parts:
                    if part.startswith("[") and part.endswith("]"):
                        vals = [float(x) for x in part[1:-1].split(",")]
                        latent_values.append(vals)
                        break

        if latent_values:
            return np.array(latent_values)

        # Alternativa: buscar archivos .npy en output
        npy_files = glob.glob(str(output_dir / "*.npy"))
        for npy_file in npy_files:
            data = np.load(npy_file)
            if data.ndim == 2 and data.shape[1] > 1:
                return data

    except Exception as e:
        log(f"  Warning al extraer latent: {e}")

    return None


# -----------------------------------------------
# Main
# -----------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="FASE 2a: Ejecutar HetSIREN")
    parser.add_argument("--dataset", required=True,
                        choices=ALL_DATASETS + ["all"],
                        help="Dataset a procesar")
    parser.add_argument("--gpu", default="0", help="GPU IDs (default: 0)")
    args = parser.parse_args()

    datasets = ALL_DATASETS if args.dataset == "all" else [args.dataset]

    results = {}
    for ds in datasets:
        ok = run_hetsiren(ds, args.gpu)
        results[ds] = "OK" if ok else "FAILED"

    log("\n=== RESUMEN HETSIREN ===")
    for name, status in results.items():
        log(f"  {name}: {status}")

    log("\nSiguiente paso: python scripts/04_run_cryodrgn.py --dataset ...")


if __name__ == "__main__":
    main()
